### ISSUE TITLE
RBTree 

### ISSUE THREAD

**Issue by tslilyai** [nathanielherman/sto#5]
TODOs:

* Node representation: {std::pair<const K key; T value>; version; rblinks;} (potentially using versioned values with the pair as the value) (@huangyihe)
* Absent reads (@tslilyai)
  * tree version has a special key, added to read set for absent reads
  * inserts/deletes change the tree version
* Add to read/write sets as follows: 
  * Sto::item(this, ptr_node).add_read(node->version);
  * Sto::item(this, ptr_node).add_write(node->value);
  * values of read/write sets should be versions
* Garbage collection (rcu) for erases at commit time (@tslilyai)
  * abort upon seeing delete_bit set unless read_my_writes

**Comment by tslilyai** [comment]
Seems like we both were working on the same thing at the same time... I added treelock and rmw for insert_update and find_or_abort, so let me know if there's something you see that got messed up!

**Comment by huangyihe** [comment]
I've already updated the `rpwrapper` layout -- not a difficult task at all. I can either start to write some tests or help with absent reads/rcu "real" delete. Probably we should agree on what kind of bit-tricks we want to play with the STO keys first?

**Comment by tslilyai** [comment]
Bit tricks? What do you mean? I just set tree_key_ to be a unique "pointer"
key.

On Mon, Sep 28, 2015 at 12:56 PM, Yihe (William) Huang <
notifications@github.com> wrote:

> I've already updated the rpwrapper layout -- not a difficult task at all.
> I can either start to write some tests or help with absent reads/rcu "real"
> delete. Probably we should agree on what kind of bit-tricks we want to play
> with the STO keys first?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanielherman/sto/issues/5#issuecomment-143803667>.
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by huangyihe** [comment]
Yep tree key should be a unique pointer (to `rbwrapper` right?), so we are gonna shift version-type keys (STO keys used to identify versions instead of nodes) left by one bit and set the LSB?

**Comment by tslilyai** [comment]
well, we technically only have version-type key right now (the
treeversion), so we can just actually set it to be 1....
(did you see the changes i pushed with treeversion and treekey?)

On Mon, Sep 28, 2015 at 12:59 PM, Yihe (William) Huang <
notifications@github.com> wrote:

> Yep tree key should be a unique pointer (to rbwrapper right?), so we are
> gonna shift version-type keys (STO keys used to identify versions instead
> of nodes) left by one bit and set the LSB?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanielherman/sto/issues/5#issuecomment-143804478>.
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by huangyihe** [comment]
Yeah I see it... It's causing a bunch of weird syntax errors (probably `git` is to blame...); fixing it right now.

**Comment by huangyihe** [comment]
Okay cool, yeah we can absolutely just set it to 1 for now...

**Comment by huangyihe** [comment]
Oops when I was talking about "tree keys" previously I meant "node keys"... Tree key is for the whole tree (the 0x1 we have right now).

**Comment by tslilyai** [comment]
I think node keys we can actually just use the pointer, right?

On Mon, Sep 28, 2015 at 1:15 PM, Yihe (William) Huang <
notifications@github.com> wrote:

> Oops when I was talking about "tree keys" previously I meant "node
> keys"... Tree key is for the whole tree (the 0x1 we have right now).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanielherman/sto/issues/5#issuecomment-143807953>.
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by huangyihe** [comment]
Yes, that's what I did. I just switched all `versioned_value*` pointers to `rbwrapper*` pointers (returned by `find_or_abort()`). We'd better use pointers because otherwise we will trigger that template beast Eddie talked about...

**Comment by huangyihe** [comment]
I reworked a little bit on our `check()` and `install()` methods to address the interface changes in `rbwrapper`. I think we should probably defer incrementing `treeversion_` (currently in `install`) until later in `cleanup()`? Otherwise we keep conflicting with ourselves in the same transaction which doesn't make much sense...

We also need to modify our `insert()`/`operator[]` such that delete-then-insert is treated as an update and removes the delete tag. `install` doesn't do `rcu_free()` yet, but otherwise looks okay to me now.

**Comment by tslilyai** [comment]
I think cleanup is only if we need to abort? After we install, we shouldn't
need to cleanup (because we've committed).

On Mon, Sep 28, 2015 at 4:03 PM, Yihe (William) Huang <
notifications@github.com> wrote:

> I reworked a little bit on our check() and install() methods to address
> the interface changes in rbwrapper. I think we should probably defer
> incrementing treeversion_ (currently in install) until later in cleanup()?
> Otherwise we keep conflicting with ourselves in the same transaction which
> doesn't make much sense...
>
> We also need to modify our insert()/operator[] such that
> delete-then-insert is treated as an update and removes the delete tag.
> install doesn't do rcu_free() yet, but otherwise looks okay to me now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanielherman/sto/issues/5#issuecomment-143859405>.
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by huangyihe** [comment]
`cleanup()` is called either way, right? (I think so because I see it [here](https://github.com/nathanielherman/sto/blob/369da4bb19495d28653f44dd784e3eb4281c0cfb/Transaction.hh#L668)). I think we can't increment `treeversion_` in `install()`, because otherwise `count()` (which observes `treeversion_`) and `insert()`/`erase()` in the same transaction will always conflict; so if a transaction does a `count()` and then an `insert()`, then it will just keep aborting itself until the world ends...

**Comment by tslilyai** [comment]
Oh yeah you're right!  But we don't do anything if the "committed" argument
is "true".

I'm pretty sure we do all the checks before the installs? So it should be
fine the increment treeversion_ in install?

On Mon, Sep 28, 2015 at 8:07 PM, Yihe (William) Huang <
notifications@github.com> wrote:

> cleanup() is called either way, right? (I think so because I see it here
> <https://github.com/nathanielherman/sto/blob/369da4bb19495d28653f44dd784e3eb4281c0cfb/Transaction.hh#L668>).
> I think we can't increment treeversion_ in install(), because otherwise
> count() (which observes treeversion_) and insert()/erase() in the same
> transaction will always conflict; so if a transaction does a count() and
> then an insert(), then it will just keep aborting itself until the world
> ends...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanielherman/sto/issues/5#issuecomment-143907423>.
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by huangyihe** [comment]
Oops my bad... you are right, check is phase 2... Great, we don't have to move it then!

**Comment by tslilyai** [comment]
:D
what's with the const_cast? we weren't having compiler errors with types
before, were we?

On Mon, Sep 28, 2015 at 8:25 PM, Yihe (William) Huang <
notifications@github.com> wrote:

> Oops my bad... you are right, check is phase 2... Great, we don't have to
> move it then!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanielherman/sto/issues/5#issuecomment-143909786>.
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by tslilyai** [comment]
Also, I added actually erasing items to install and cleanup, plus some
other comments (XXX) that I'm not sure about! LMK what you think :D

I'll start writing test cases tomorrow for non-transactional and
transactional sequences of function calls!

On Mon, Sep 28, 2015 at 10:45 PM, Lily Tsai <lilliantsai@college.harvard.edu
> wrote:

> :D
> what's with the const_cast? we weren't having compiler errors with types
> before, were we?
>
> On Mon, Sep 28, 2015 at 8:25 PM, Yihe (William) Huang <
> notifications@github.com> wrote:
>
>> Oops my bad... you are right, check is phase 2... Great, we don't have to
>> move it then!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nathanielherman/sto/issues/5#issuecomment-143909786>.
>>
>
>
>
> --
> Lillian Tsai
> Harvard University | Class of 2017
> A.B. Degree Candidate in Computer Science and Mathematics
> (650) 644-9845 | lilliantsai@college.harvard.edu
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by huangyihe** [comment]
Great! I'm actually looking at implementing read-my-writes and it seems to me that our current `insert_update` is just super broken... :)

`const_cast` is just there to get rid of the `const` quantifier so that I can use `this` in `Sto::new_item()`. I saw that the `std::map::count` interface is a `const` method, so I changed ours to a `const` method as well and that gave me some compiler errors (and BTW we never instantiated `count` and `erase` before either lol).

I gave it a rough pass and I don't think there are any problems (as far as I can tell). We could potentially not remove a node from the tree when an insertion fails (because a common thing for an aborted transaction to do is to retry), but for now it looks perfectly reasonable just to remove it and play safe.

**Comment by tslilyai** [comment]
Haha.. I'll look at that insert_update again...

So if something is a const method, we need to cast "this" (the instance of
the tree) to be non-const?  Why is the tree const if the method is const?


On Mon, Sep 28, 2015 at 11:30 PM, Yihe (William) Huang <
notifications@github.com> wrote:

> Great! I'm actually looking at implementing read-my-writes and it seems to
> me that our current insert_update is just super broken... :)
>
>


-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by tslilyai** [comment]
I think I addressed setting and checking delete/insert_bit in insert_update
-- LMK what you think (and we can walk through it tomorrow too).

On Tue, Sep 29, 2015 at 8:06 AM, Lily Tsai <lilliantsai@college.harvard.edu>
wrote:

> Haha.. I'll look at that insert_update again...
>
> So if something is a const method, we need to cast "this" (the instance of
> the tree) to be non-const?  Why is the tree const if the method is const?
>
>
> On Mon, Sep 28, 2015 at 11:30 PM, Yihe (William) Huang <
> notifications@github.com> wrote:
>
>> Great! I'm actually looking at implementing read-my-writes and it seems
>> to me that our current insert_update is just super broken... :)
>>
>>
>
>
> --
> Lillian Tsai
> Harvard University | Class of 2017
> A.B. Degree Candidate in Computer Science and Mathematics
> (650) 644-9845 | lilliantsai@college.harvard.edu
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by huangyihe** [comment]
Ideally we shouldn't cast anything from `const` to non-`const` because that may invoke nasal demons... The problem in our case is that `Sto::new_item()` always takes a non-`const` pointer as one of the arguments, and I have no way of making the base class mutable only... so I went for the last resort to do a `const_cast`...

Our `insert_update()` still doesn't add anything to the read set... `operator[]` is basically just `insert_update` right now, so we probably need to add stuff to the read set there? And also I think `insert_update` should be the place where we like ***really*** handle read-my-writes? Like checking our own buffered writes and returning a buffered write value if any.

**Comment by tslilyai** [comment]
Hm... let's ask Eddie about this? (the const thing)

Also, insert_update() invokes find_or_abort(), which adds items to the read
set.  And yeah, we should probably do that... except we actually *do*
writes when we insert items, right?  So we would return our buffered writes
regardless.

On Tue, Sep 29, 2015 at 10:22 AM, Yihe (William) Huang <
notifications@github.com> wrote:

> Ideally we shouldn't cast anything from const to non-const because that
> may invoke nasal demons... The problem in our case is that Sto::new_item()
> always takes a non-const pointer as one of the arguments, and I have no
> way of making the base class mutable only... so I went for the last resort
> to do a const_cast...
>
> Our insert_update() still doesn't add anything to the read set...
> operator[] is basically just insert_update right now, so we probably need
> to add stuff to the read set there? And also I think insert_update should
> be the place where we like *really* handle read-my-writes? Like checking
> our own buffered writes and returning a buffered write value if any.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanielherman/sto/issues/5#issuecomment-144075634>.
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by huangyihe** [comment]
Hmm I don't see `find_or_abort()` ever add anything other than the `treeversion_` to the read set... I also don't think we should do `add_read()` that early -- inserts (like `map[5]=3`) also calls `find_or_abort()`, but that need not add anything to the read set I think?

**Comment by tslilyai** [comment]
I saw your changes -- I added the item versions to the read sets as well in
insert_update, but I'm not quite sure if that's correct (I'll have to think
about it more)

On Tue, Sep 29, 2015 at 12:00 PM, Yihe (William) Huang <
notifications@github.com> wrote:

> Hmm I don't see find_or_abort() ever add anything other than the
> treeversion_ to the read set... I also don't think we should do add_read()
> that early -- inserts (like map[5]=3) also calls find_or_abort(), but
> that need not add anything to the read set I think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanielherman/sto/issues/5#issuecomment-144103376>.
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by tslilyai** [comment]
I'm not quite sure this is correct:

        tree[55] = 56;
        tree[57] = 58;
        Sto::set_transaction(&t2);
        int x = tree[58];
        assert(x == 0);
        assert(t2.try_commit());
        Sto::set_transaction(&t1);
        assert(!t1.try_commit());

I think that t1 should actually be able to commit, because we aren't adding
treeversion_ to our read set for this particular case (inserting an element
when none exist).  If t2 had tried to modify the same nodes / insert the
same node (57 or 55), then t2 would have aborted due to insert_bit.

On Tue, Sep 29, 2015 at 7:03 PM, Lily Tsai <lilliantsai@college.harvard.edu>
wrote:

> I saw your changes -- I added the item versions to the read sets as well
> in insert_update, but I'm not quite sure if that's correct (I'll have to
> think about it more)
>
> On Tue, Sep 29, 2015 at 12:00 PM, Yihe (William) Huang <
> notifications@github.com> wrote:
>
>> Hmm I don't see find_or_abort() ever add anything other than the
>> treeversion_ to the read set... I also don't think we should do
>> add_read() that early -- inserts (like map[5]=3) also calls
>> find_or_abort(), but that need not add anything to the read set I think?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nathanielherman/sto/issues/5#issuecomment-144103376>.
>>
>
>
>
> --
> Lillian Tsai
> Harvard University | Class of 2017
> A.B. Degree Candidate in Computer Science and Mathematics
> (650) 644-9845 | lilliantsai@college.harvard.edu
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by huangyihe** [comment]
I tried it and `t1` didn't seem to be able to commit... because we are adding reads in `find_or_abort`...?

**Comment by tslilyai** [comment]
oh yeah, we are... and we don't need to add these reads if we're
updating/inserting the node after we read, but we do need to add these
reads if we're just doing the read (i.e. for count)

On Wed, Sep 30, 2015 at 8:03 PM, Yihe (William) Huang <
notifications@github.com> wrote:

> I tried it and t1 didn't seem to be able to commit... because we are
> adding reads in find_or_abort...?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanielherman/sto/issues/5#issuecomment-144578183>.
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by huangyihe** [comment]
Exactly. Can we just lock around `find_or_abort()` to solve this problem? (So that we don't have to `add_read()` in `find_or_abort()` at all -- we only do `add_read()` depending on what we are doing with the returned node later in `insert_update()` or `erase()`)

**Comment by tslilyai** [comment]
do you want to just work in rbtree, instead of rbtree_test? i'm not sure
where to make the changes...

On Wed, Sep 30, 2015 at 8:59 PM, Yihe (William) Huang <
notifications@github.com> wrote:

> Exactly. Can we just lock around find_or_abort() to solve this problem?
> (So that we don't have to add_read() in find_or_abort() at all -- we only
> do add_read() depending on what we are doing with the returned node later
> in insert_update() or erase())
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanielherman/sto/issues/5#issuecomment-144586594>.
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by tslilyai** [comment]
it already seems like we add reads of tree_version as necessary in erase
and count...

On Wed, Sep 30, 2015 at 9:07 PM, Lily Tsai <lilliantsai@college.harvard.edu>
wrote:

> do you want to just work in rbtree, instead of rbtree_test? i'm not sure
> where to make the changes...
>
> On Wed, Sep 30, 2015 at 8:59 PM, Yihe (William) Huang <
> notifications@github.com> wrote:
>
>> Exactly. Can we just lock around find_or_abort() to solve this problem?
>> (So that we don't have to add_read() in find_or_abort() at all -- we
>> only do add_read() depending on what we are doing with the returned node
>> later in insert_update() or erase())
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nathanielherman/sto/issues/5#issuecomment-144586594>.
>>
>
>
>
> --
> Lillian Tsai
> Harvard University | Class of 2017
> A.B. Degree Candidate in Computer Science and Mathematics
> (650) 644-9845 | lilliantsai@college.harvard.edu
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by huangyihe** [comment]
Oh I'm implementing a test harness on branch rbtree_test. If you want to modify the tree just feel free to do it on rbtree (thank you autocorrect for keeping correcting it to "retry").

**Comment by tslilyai** [comment]
Yeah I saw -- I'm figuring out how you're running the tests so I can help
out! I literally just removed the read of treeversion_ in find_or_abort....
because we're actually handling it correctly in count and erase already.

On Wed, Sep 30, 2015 at 9:10 PM, Yihe (William) Huang <
notifications@github.com> wrote:

> Oh I'm implementing a test harness on branch rbtree_test. If you want to
> modify the tree just feel free to do it on rbtree (thank you autocorrect
> for keeping correcting it to "retry").
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanielherman/sto/issues/5#issuecomment-144588491>.
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by tslilyai** [comment]
Your test harness is for testing serializability, right?

I'm going to write test cases (similar to the one you added) to make sure
we're aborting correctly and doing read_my_writes.... I don't see any easy
way to automate this, so I'll probably write tests manually to catch all
the corner cases

We can also write a fuzz testing harness later to just see if we get any
unexpected results

On Wed, Sep 30, 2015 at 9:12 PM, Lily Tsai <lilliantsai@college.harvard.edu>
wrote:

> Yeah I saw -- I'm figuring out how you're running the tests so I can help
> out! I literally just removed the read of treeversion_ in find_or_abort....
> because we're actually handling it correctly in count and erase already.
>
> On Wed, Sep 30, 2015 at 9:10 PM, Yihe (William) Huang <
> notifications@github.com> wrote:
>
>> Oh I'm implementing a test harness on branch rbtree_test. If you want to
>> modify the tree just feel free to do it on rbtree (thank you autocorrect
>> for keeping correcting it to "retry").
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nathanielherman/sto/issues/5#issuecomment-144588491>.
>>
>
>
>
> --
> Lillian Tsai
> Harvard University | Class of 2017
> A.B. Degree Candidate in Computer Science and Mathematics
> (650) 644-9845 | lilliantsai@college.harvard.edu
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by huangyihe** [comment]
Great. `Sto::set_transaction()` is really handy. We should probably test roll-back (abort-cleanup) as well.

**Comment by huangyihe** [comment]
Ah, and yes, I am trying to test serializability.

**Comment by tslilyai** [comment]
Great... we should probably go over all these test cases at some point
because I'm not sure I'm hitting all the possible conflicts.  I also
believe we're hitting a deadlock somewhere.....

On Wed, Sep 30, 2015 at 9:22 PM, Yihe (William) Huang <
notifications@github.com> wrote:

> Ah, and yes, I am trying to test serializability.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanielherman/sto/issues/5#issuecomment-144589554>.
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu

**Comment by tslilyai** [comment]
I pushed tests for erase/count conflicts between two transactions (I'll do
the other permutations of function calls -- erase/update, update/count,
etc. as well)

I had to change a few of our read/write set invariants (i.e. we do need to
add a read of the item when we delete it, because another transaction may
have deleted it in the past and not yet committed).

Let me know if you see something off with what I did!

On Wed, Sep 30, 2015 at 9:46 PM, Lily Tsai <lilliantsai@college.harvard.edu>
wrote:

> Great... we should probably go over all these test cases at some point
> because I'm not sure I'm hitting all the possible conflicts.  I also
> believe we're hitting a deadlock somewhere.....
>
> On Wed, Sep 30, 2015 at 9:22 PM, Yihe (William) Huang <
> notifications@github.com> wrote:
>
>> Ah, and yes, I am trying to test serializability.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nathanielherman/sto/issues/5#issuecomment-144589554>.
>>
>
>
>
> --
> Lillian Tsai
> Harvard University | Class of 2017
> A.B. Degree Candidate in Computer Science and Mathematics
> (650) 644-9845 | lilliantsai@college.harvard.edu
>



-- 
Lillian Tsai
Harvard University | Class of 2017
A.B. Degree Candidate in Computer Science and Mathematics
(650) 644-9845 | lilliantsai@college.harvard.edu
